version: '3.5'

name: wineflowmanager

services:

  mysql-db-users:
    image: mysql:8.0.26
    restart: always
    expose:
      - 3306
    #ports:
    #  - 3306:3306
    environment:
      - MYSQL_USER=uporabniki
      - MYSQL_PASSWORD=uporabniki
      - MYSQL_DATABASE=uporabniki
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-db-users:/var/lib/mysql
    networks:
        - native

  users:
    container_name: users-container
    image: mtvrt123/wineflowmanager-users:latest
    #ports:
    #  - "8081:8080"
    #  - "9000:9000"
    expose:
      - 8080
      - 9000
    networks:
      - native
    depends_on:
      - mysql-db-users
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql-db-users:3306/uporabniki
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
    #volumes:
    #  - users:/deployments
    restart: always

  #####################################################################################
  
  mysql-db-vinograds:
    image: mysql:8.0.26
    restart: always
    expose:
      - 3306
    #ports:
      #- 3306:3306
    environment:
      - MYSQL_USER=vinograd
      - MYSQL_PASSWORD=vinograd
      - MYSQL_DATABASE=vinograds
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-db-vinograds:/var/lib/mysql
    networks:
        - native

  rabbitmq:
    container_name: rabbitmq-container
    image: mtvrt123/wineflowmanager-rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    networks:
      - native
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./vinogradservice/definitions.json:/etc/rabbitmq/definitions.json

  vinograds:
    container_name: vinograds-container
    image: mtvrt123/wineflowmanager-vinograds:latest
    #ports:
    #  - "8082:8080"
    #  - "9000:9000"
    expose:
      - 8080
    networks:
      - native
    depends_on:
      - mysql-db-vinograds
      - rabbitmq
    environment:
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:mysql://mysql-db-vinograds:3306/vinograds
    #volumes:
    #  - vinograds:/deployments
    restart: always

  #####################################################################################

  mysql-db-winestorage:
      image: mysql:8.0.26
      restart: always
      expose:
          - 3306
      #ports:
      #    - 3306:3306
      environment:
        - MYSQL_USER=winestorage
        - MYSQL_PASSWORD=winestorage
        - MYSQL_DATABASE=winestorage
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_HOST:%
      networks:
          - native
      volumes:
        - mysql-db-winestorage:/var/lib/mysql

  winestorage:
      container_name: winestorage-container
      image: mtvrt123/wineflowmanager-winestorage:latest
      restart: always
      #ports:
      #    - 8180:8180
      expose:
          - 8180
      environment:
          - SPRING_PROFILES_ACTIVE=mysql
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root
          - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db-winestorage:3306/winestorage
      depends_on:
          - mysql-db-winestorage
      entrypoint: ["java", "-jar", "-Dspring.profiles.active=mysql","/app.jar"]
      networks:
          - native

  #####################################################################################
  
  web-gateway:
    container_name: web-gateway-container
    image: mtvrt123/wineflowmanager-web-gateway:latest
      #target: dev
    environment:
      - uporabnik_url=http://users:9000
      - vino_url=http://winestorage:8180/api/v1/
      - vinograd_url=http://vinograds:8080/
    #expose:
    #  - 8080
    ports:
      - "8080:8080"
    networks:
      - native
    restart: always

  mobile-gateway:
    container_name: mobile-gateway-container
    image: mtvrt123/wineflowmanager-mobile-gateway:latest
      #target: dev
    environment:
      - uporabnik_url=http://users:9000
      - vino_url=http://winestorage:8180/api/v1/
      - vinograd_url=http://vinograds:8080/
    #expose:
    #  - 8080
    ports:
      - "8081:8080"
    networks:
      - native
    restart: always

  #####################################################################################

  webapp:
    container_name: webapp-container
    depends_on:
      - web-gateway
      - mobile-gateway
    image: mtvrt123/wineflowmanager-webapp:latest
    #expose:
    #  - 3000
    #  - 3001
    #  - 3002
    #  - 3003
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    networks:
      - native
    restart: always

    ####################################################################

  #webapp_app1:
  #  container_name: webapp_app1_container
  #  build:
  #    context: webapp/app1
  #    dockerfile: Dockerfile
  #  expose:
  #    - 3001
  #  #ports:
  #  #  - "3001:3001"
  #  networks:
  #    - native
  #  restart: always
  #  command: npm start
#
  #webapp_app2:
  #  container_name: webapp_app2_container
  #  build:
  #    context: webapp/app2
  #    dockerfile: Dockerfile
  #  expose:
  #    - 3002
  #  #ports:
  #  #  - "3002:3002"
  #  networks:
  #    - native
  #  restart: always
  #  command: npm start
#
  #webapp_app3:
  #  container_name: webapp_app3_container
  #  build:
  #    context: webapp/app3
  #    dockerfile: Dockerfile
  #  expose:
  #    - 3003
  #  #ports:
  #  #  - "3003:3003"
  #  networks:
  #    - native
  #  restart: always
  #  command: npm start
#
  #wabapp_shell:
  #  container_name: webapp_shell_container
  #  build:
  #    context: webapp/shell
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - webapp_app1
  #    - webapp_app2
  #    - webapp_app3
  #  expose:
  #    - 3000
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - native
  #  restart: always
  #  command: npm start


networks:
  native:
    name: native-network
    driver: bridge

volumes:
  mysql-db-users:
  mysql-db-vinograds:
  mysql-db-winestorage:
