apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mysql-db-users
  name: mysql-db-users
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql-db-users
