apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-db-vinograds
  name: mysql-db-vinograds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
