apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/native-network: "true"
        io.kompose.service: users
    spec:
      containers:
        - env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mysql://mysql-db-users:3306/uporabniki
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: root
            - name: QUARKUS_DATASOURCE_USERNAME
              value: root
          image: mtvrt123/wineflowmanager-users:latest
          name: users-container
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
