apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: users
  name: users
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: users
