apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: vinograds
  name: vinograds
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vinograds
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/native-network: "true"
        io.kompose.service: vinograds
    spec:
      containers:
        - env:
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: root
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: vertx-reactive:mysql://mysql-db-vinograds:3306/vinograds
            - name: QUARKUS_DATASOURCE_USERNAME
              value: root
          image: mtvrt123/wineflowmanager-vinograds:latest
          name: vinograds-container
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
