apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: web-gateway
  name: web-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/native-network: "true"
        io.kompose.service: web-gateway
    spec:
      containers:
        - env:
            - name: uporabnik_url
              value: http://users:9000
            - name: vino_url
              value: http://winestorage:8180/api/v1/
            - name: vinograd_url
              value: http://vinograds:8080/
          image: mtvrt123/wineflowmanager-web-gateway:latest
          name: web-gateway-container
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
