apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapp
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/native-network: "true"
        io.kompose.service: webapp
    spec:
      containers:
        - image: mtvrt123/wineflowmanager-webapp:latest
          name: webapp-container
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
            - containerPort: 3002
              hostPort: 3002
              protocol: TCP
            - containerPort: 3003
              hostPort: 3003
              protocol: TCP
      restartPolicy: Always
