apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: winestorage
  name: winestorage
spec:
  ports:
    - name: "8180"
      port: 8180
      targetPort: 8180
  selector:
    io.kompose.service: winestorage
