apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: winestorage
  name: winestorage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: winestorage
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s-local.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/native-network: "true"
        io.kompose.service: winestorage
    spec:
      containers:
        - command:
            - java
            - -jar
            - -Dspring.profiles.active=mysql
            - /app.jar
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db-winestorage:3306/winestorage
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
          image: mtvrt123/wineflowmanager-winestorage:latest
          name: winestorage-container
          ports:
            - containerPort: 8180
              protocol: TCP
      restartPolicy: Always
