version: '3.5'

services:

  mysql_db:
    image: mysql:8.0.26
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=uporabniki
      - MYSQL_PASSWORD=uporabniki
      - MYSQL_DATABASE=uporabniki
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
        - mysql-native

  users:
    container_name: users_container
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - mysql-native
    depends_on:
      - mysql_db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql_db:3306/uporabniki
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
    volumes:
      - users:/deployments
    restart: unless-stopped

networks:
  mysql-native:
    name: mysql-native-network
    driver: bridge

volumes:
  mysql_db:
  users:
