name: Run unit tests

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        working-directory: ./uporabnikiservice
        run: mvn -B package --file pom.xml

      - name: Prepare JAR for upload
        working-directory: ./uporabnikiservice
        run: mkdir build && cp target/*.jar build

      - name: Upload resulting JAR
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build

  push_to_registry-grpc-quarkus:
    runs-on: ubuntu-latest
    needs: build-test-package

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: create target directory
        run: mkdir target

      - name: Build and test with Maven
        working-directory: ./uporabnikiservice
        run: mvn package -Dnative --define quarkus.native.container-build=true

      - name: Prepare JAR for upload
        working-directory: ./uporabnikiservice
        run: mkdir build && cp target/*-runner build

      - name: Upload resulting JAR
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          file: ./uporabnikiservice/src/main/docker/Dockerfile.native
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/uporabnikiservice:latest

  